### ISSUE TITLE
PFT timeouts

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1743]
We've seen a number of timeouts in our alerts recently. @maeve-fpf will investigate whether bumping up resources stops those.

[update 11/15] Next steps here are for the web team to investigate the performance of the export endpoint. (Personally I'd like to see the export endpoint and the API unified so we don't have either diverging features or performance. Export links are functionally basically API calls with a CSV output format.)

**Comment by chigby** [comment]
The last time I looked into this it was part of #1573

**Comment by chigby** [comment]
Example of [a segment of logs leading up to the worker timeout event](https://logs.freedom.press/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-02T20:40:00.000Z',to:'2023-10-02T20:43:00.000Z'))&_a=(columns:!(django.event,django.response.status_code,duration_ms,django.request.path_info,django.request.meta.QUERY_STRING),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:django.request.path_info,negate:!t,params:(query:%2Fhealth%2Fok%2F),type:phrase),query:(match_phrase:(django.request.path_info:%2Fhealth%2Fok%2F))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.cluster_name,negate:!f,params:(query:www-production),type:phrase),query:(match_phrase:(resource.labels.cluster_name:www-production))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'filebeat-*',key:resource.labels.namespace_name,negate:!f,params:(query:pressfreedomtracker),type:phrase),query:(match_phrase:(resource.labels.namespace_name:pressfreedomtracker)))),index:'filebeat-*',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))):

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/561931/096500de-156b-499c-95e4-4b9a9807cd8c)

(screenshot in case it's easier to see).

**Comment by soleilera** [comment]
@maeve-fpf will continue investigation on resource allocation to improve performance. We also created a web team card to timebox a performance investigation on the web app side.

**Comment by maeve-fpf** [comment]
We've pushed memory request/limit increases for the Django pods, and will continue to monitor for another 2 weeks then close.

**Comment by soleilera** [comment]
It's been 2 weeks and I believe PFT timeouts are no longer an issue so I think we can close this, but defer to @maeve-fpf.

**Comment by harrislapiroff** [comment]
We're still seeing occasional timeouts, most recently on 11/10. It may be that the next step is on the web team to investigate performance of specific endpoints. I recall we have a conversation about this at web sync recently, does anyone remember the conclusion there? (attn @chigby @SaptakS)

**Comment by chigby** [comment]
I think we said we were going to investigate the "export" function?

**Comment by harrislapiroff** [comment]
That sounds right to me. Maybe the next steps here belong to the web team @soleilera. I'll bounce this to our hi pri list

**Comment by chigby** [comment]
We haven't seen timeouts in several weeks, closing in favor of #1802
